### ISSUE TITLE
Bug: edgehandle is exported as node with cy.json()

### ISSUE THREAD

**Issue by mafar** [cytoscape/cytoscape.js-edgehandles#100]
see the fiddle here https://jsfiddle.net/bababalcksheep/uuhwytx2/2/

1. I only have one element in cy
1. I hove over that element ,``` edgehandle```  appears and then I press export
1. printing ```cy.json().elements.nodes``` shows that now it has 2 nodes instead of one

**Is there a way to avoid exporting edgehandles as nodes ?**

![picture2](https://user-images.githubusercontent.com/4101480/35603410-152c1ed8-065f-11e8-9a1d-dca23cf01f88.png)

**Comment by maxkfranz** [comment]
Readme: hide() : remove the handle node from the graph

Call `eh.hide()`

**Comment by mafar** [comment]
Yes. It works.
