### ISSUE TITLE
edgeType() doesn't support null/undefined return

### ISSUE THREAD

**Issue by aprudnikoff** [cytoscape/cytoscape.js-edgehandles#101]
According to a code in drawing.js there are only 2 cases supported: 'node' and else which is treated as 'flat' indeed.

There's no way disable creating edges to particular nodes.

It worked in 2.15.0

**Comment by maxkfranz** [comment]
Works on the demo page on master/3.2.0

```js
~ 144         var eh = cy.edgehandles({
+ 145           edgeType: ( src, tgt ) => null
+ 146         });
```

**Comment by aprudnikoff** [comment]
It's still reproducible for me on master/3.2.0
https://jsfiddle.net/fq3vnkj0/4/
