### ISSUE TITLE
Hiding edgehandles bug

### ISSUE THREAD

**Issue by ketysek** [cytoscape/cytoscape.js-edgehandles#102]
Hello, in previous release, my code for hiding edgehandles worked well, but now in version 3.2.0 it hides also node (not only edgehandle).

```
componentDidMount() {
    if(this.cy === null) {
      const container = {
        container: this.containerDOM
      }

      this.cy = cytoscape(
        Object.assign({}, container, cytoscapeDefaults)
      )

      this.eh = this.cy.edgehandles({
        loopAllowed: () => { return false }
      })

      const self = this
      document.getElementById("cytoscape").addEventListener("mouseout", function() {
          //self.eh.hide()
      })
   }
}

```

### EDIT
Okay, it seems like it's not related to edgehandles version ... so maybe with cytoscape version.

### EDIT 2
In firefox it's okay, so the cytoscape also is not the problem I think ... 
Problem appears in Google Chrome Version 64.0.3282.140 (Official Build) (64-bit) ... anyone could confirm this?

### EDIT 3
I've tried older versions (edge handles 3.0.2 and cytoscape 3.2.5) and it's pretty weird ... first few attempts to hide edgehandle works well (only eh dissapears) ... but after some time it's the same problem

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js/issues/2059

Chrome v64 has broken canvas support when it's GPU-accelerated.
