### ISSUE TITLE
enable and disable methods error when called: options[type] is undefined

### ISSUE THREAD

**Issue by xeinherjar** [cytoscape/cytoscape.js-edgehandles#108]
Using 3.2.3, enable() and disable() error when called.

```
const a = cy.edgehandles()
a.disable()  
```
Will error with  `options[type] is undefined` in FireFox and `TypeError: Cannot read property 'apply' of undefined` in Chrome

**Comment by maxkfranz** [comment]
Addressed in 3.2.4
