### ISSUE TITLE
Undocumented change to edgeType-behavior

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js-edgehandles#113]
When upgrading to the latest version from 2.x - there's an undocumented change in behavior to how `edgeType` interacts with the rest of the graph.

Our implementation of `edgeType` looks as follows, and blocks the user from building certain graphs that's invalid in our system. However, previously, preview-edges were not included in traversals of the graph in `edgeType`, while now it seems they are? 

````
				edgeType: function(source, target){
					if(target.is('[!group][?initialized]')){
						if(target.neighbourhood().anySame(source)){
							return false;
						}else{
							return 'flat';
						}
					}else{
						return false;
					}
				}, 
````

This now (verified via logging) returns 'flat' for the preview-edge, but when releasing is re-run for the "real" edge, which then (of course) returns false. 

Is this intended?

**Comment by buffpojken** [comment]
As far as I can tell, this is now required to accomplish the same thing: 

````
				edgeType: function(source, target){
					if(target.is('[!group][?initialized]')){
						let gather = target.neighbourhood();
						let actual = gather.filter(function(el){
							return !el.hasClass('eh-preview-active') 
						})
						console.log(actual)
						if(actual.anySame(source)){
							return false;
						}else{
							return 'flat';
						}
					}else{
						return false;
					}
				}, 
````

**Comment by maxkfranz** [comment]
You have to filter out the edges, as v3 always adds preview elements.

**Comment by maxkfranz** [comment]
I think it's just the classes for now.  I suppose there could be a scratch field.

**Comment by buffpojken** [comment]
Hmm. Scratch can't be accessed by selectors though? Since neighbourhood already supports the filter-option, being able to filter them straight from that would be neat?

**Comment by dwagin** [comment]
#118
