### ISSUE TITLE
Is toggleOffOnLeave removed on purpose or would a PR be accepted? 

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js-edgehandles#114]
We use toggleOffOnLeave to cleanup the UI which is now removed. Is there a good reason for its removal or would a PR be accepted?

**Comment by maxkfranz** [comment]
v3 is a rewrite.  It has a better codebase and it simplifies things based on what users do by and large.  Users very rarely understand the multiple edges option, they sometimes use the handle itself, and they prefer draw mode with a toggle button by a large margin.  If you want to use the multiple edges feature, you can safely stick with v2.  I don't think it's worth the maintenance cost for v3, given that users tend to not understand it.

**Comment by buffpojken** [comment]
Fair enough. I'll meditate on how we'll proceed then - but the new "handle is a regular node with regular styling" is pretty neat and allows us to do a lot of neat things. Thanks for the quick reply!

**Comment by maxkfranz** [comment]
Yes, maybe there's a way to style the handle node to make it more intuitive to users.  I haven't found one yet.  If you do, it would be great if you would post it somewhere so it could be in one of the demos.
