### ISSUE TITLE
Issue when shape is defined as a function

### ISSUE THREAD

**Issue by kranthitechie** [cytoscape/cytoscape.js-edgehandles#117]
My application seems to run fine when I defined the node shapes as a stirng like 'ellipse' or roundrectangle

if I define the shape as a function of the node, I am running into an error like this

cytoscape.js:21814 Uncaught TypeError: Cannot read property 'intersectLine' of undefined
    at Renderer.BRp.findEdgeControlPoints (cytoscape.js:21814)
    at Renderer.BRp.recalculateEdgeProjections (cytoscape.js:22513)
    at Renderer.BRp.recalculateRenderedStyle (cytoscape.js:23238)
    at Object.updateEleCalcs [as fn] (cytoscape.js:23164)
    at beforeRenderCallbacks (cytoscape.js:25994)
    at renderFn (cytoscape.js:26013)

**Comment by maxkfranz** [comment]
I could not reproduce this on the latest release.  Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  Any of the example demos on [js.cytoscape.org](http://js.cytoscape.org) can be forked on JSBin to easily provide a code sample.Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  Any of the example demos on [js.cytoscape.org](http://js.cytoscape.org) can be forked on JSBin to easily provide a code sample.
