### ISSUE TITLE
Warning: Do not assign mappings to elements without corresponding data

### ISSUE THREAD

**Issue by enodr** [cytoscape/cytoscape.js-edgehandles#119]
Hi,

edgehandles raises the following warnings:

> cytoscape.min.js:23 Do not assign mappings to elements without corresponding data (i.e. ele `89d6e585-e41f-441e-80e0-2d2447c04254` has no mapping for property `label` with data field `name`); try a `[name]` selector to limit scope to elements with `name` defined

That might be because the "ghost" handle doesn't have a label. Using an empty label (i.e.: '') might solve this issue?

The official demo exhibits this behavior, just open the console and draw a new edge to see the warnings:
https://cytoscape.org/cytoscape.js-edgehandles/

Although not strictly a bug, if these warnings could be avoided, that would clear up the console.

Regards and keep up the good work !

**Comment by enodr** [comment]
Just tested a quick fix in drawing.js:

line 218 change from:

```
    cy.batch( () => {
      this.handleNode = cy.add({
        classes: 'eh-handle',
        position: pos,
        grabbable: false,
        selectable: false
      });
```

to: 
```
    cy.batch( () => {
      this.handleNode = cy.add({
        classes: 'eh-handle',
        position: pos,
        grabbable: false,
        selectable: false,
        data: {label: ''}
      });
```      
That does the trick and remove the warnings.

**Comment by enodr** [comment]
One last warning remaining, but this one needs some little code fix: 

`Setting a style bypass at element creation is deprecated`

There are some `cy.add` calls passing a style attribute to the created element. I guess these should be changed to create the element without the style attribute, and then call el.style(key, value) to set the style. I really don't know why cytoscape.js has this warning but there must be a reason why this is deprecated.

**Comment by lavarith** [comment]
I ran into a related issue. To have nodes show my 'label' value in the data object, I changed my `node` style to say:
```
node {
  label: data(label)
}
```
instead of `data(id)`. It seems that `.eh-ghost-node` is also a node and so when you click on it, and a `label` doesn't exist in its data, it causes the warning to appear. The warning was suppressed by adding:
```
.eh-ghost-node {
    label: data(id);
}
```

**Comment by SousaWellington** [comment]
I solved my bug following the [lavarith](https://github.com/lavarith), ,
In graph initialization [styles](https://js.cytoscape.org/#style),  I inserted a selector that would assign `label: ''` , the `.eh-ghost-node` class, as shown in the example below.

```
{
   selector: '.eh-ghost-node',
      style: {
         'label': ''
       }
},
```
