### ISSUE TITLE
Mousing over anywhere else on the canvas should remove the handle from the graph

### ISSUE THREAD

**Issue by RosaRomeroGomez** [cytoscape/cytoscape.js-edgehandles#120]
I noticed that when you mouse over anywhere else on the canvas, you still see the handle on the last node you moused over on the graph. I think that handle should disappear if you are not selecting or hovering over nodes on the graph. Please, find attached below a screenshot of this (unfortunately, you can't see my mouse pointer but it should be there).

![screen shot 2019-03-06 at 12 46 39 pm](https://user-images.githubusercontent.com/10552785/53901930-19ea0e00-400e-11e9-963d-9695e5676b26.png)

**Comment by maxkfranz** [comment]
In practice, that would make it very hard to actually click on the handle.  And in the case of a touch device, you can't remove the handle like that or the user would never notice it.  The extension should be general and flexible.

There is a general `hide()` function, so if you want to customise the behaviour --- albeit with the previous downsides --- you can call this function on `mouseout`.
