### ISSUE TITLE
Is there a way to control whether a drop target is allowed?

### ISSUE THREAD

**Issue by culli** [cytoscape/cytoscape.js-edgehandles#121]
Maybe a node could be considered as "out only" or "locked" and shouldn't allow new edges connecting into it.  It would be nice if there was a callback we could provide to make that decision.

**Comment by maxkfranz** [comment]
That already exists.  For details, please see the readme.

**Comment by culli** [comment]
I had looked, but I didn't see it the first couple times through.

This seems to be it?
` edgeType: function( sourceNode, targetNode ){
    // can return 'flat' for flat edges between nodes or 'node' for intermediate node between them
    // returning null/undefined means an edge can't be added between the two nodes
    return 'flat';
  },`
