### ISSUE TITLE
"follow" handle position

### ISSUE THREAD

**Issue by anthonysapien** [cytoscape/cytoscape.js-edgehandles#123]
I'm wondering how feasible it would be to implement a "follow" handle position where the handle follows the mouse position relative to the center of a node. This would seem very natural as you are hovering over a node and grabbing the handle in the direction of the node that you are going to connect it to.

**Comment by maxkfranz** [comment]
It's not clear to me what this means.

**Comment by anthonysapien** [comment]
I'll try to explain it better. When you move your mouse from the canvas toward a node and pass within the edge handle hit radius, the edge handle would appear on the circumference of the node very close to the mouse cursor. If you were moving from right to left, it would appear on the right side. As you move the mouse across the node to the top, the edge handle would "follow" the mouse to the top of the node.

This is a silly example, but the closest thing to the behavior that I can quickly find:
https://codepen.io/osublake/pen/dc58db767c4871f973290ea56c799c79

Thanks for taking a look.

**Comment by maxkfranz** [comment]
That's an interesting idea, though nodes are not necessarily circles.

I think it would be simpler to use draw mode in that case:  Hit anywhere on the node to start the gesture.
