### ISSUE TITLE
Work together with autopan-on-drag extension

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js-edgehandles#124]
I use the [autopan-on-drag](https://github.com/iVis-at-Bilkent/cytoscape.js-autopan-on-drag) extension but the problem is that auto panning is not triggered by edgehandle's "ghost node".

By default the ghost node is transparent and tiny, and I thought this might be the problem:
```
      ghostNode.style({
        'background-color': 'blue',
        'width': 0.0001,
        'height': 0.0001,
        'opacity': 0,
        'events': 'no'
      });
```
For testing I've made the ghost node bigger and non-transparent, and removed `events: no`, but no success.

How can I make edgehandle's ghost node trigger auto panning?

**Comment by maxkfranz** [comment]
This doesn't seem to be a problem of this extension.  It looks like you're expecting more out of the autopan-on-drag extension than it actually supports:  If you're not dragging a node, it sounds like it's out of the scope of that extension.  Maybe the author is interested in expanding the scope of the autopan extension (e.g. by adding general `position` support).  Or maybe that's an idea for a different, more general panning extension.

**Comment by jri** [comment]
OK, I should explain more clear what I intend: the edgehandles extension allows the user to create an edge by drawing it. To my knowledge drawing is realized by a (temporary) Cytoscape edge that connects the source node with a "ghost" (= invisible) node that follows the mousecursor. Now I would expect auto-panning to kick in as soon as the ghost node reaches a viewport edge.

This would allow the user to create an edge between 2 nodes far away, that is not visible in viewport at the same time.

As edgehandles extension deploys a (ghost) node already I would expect it to trigger auto-pan just like any other node does. But it doesn't.

Is my understanding of the "ghost node" correct?

The mentioned code fragment is original edgehandles code from `src/edgehandles/drawing.js`:
```js
      ghostNode.style({
        'background-color': 'blue',
        'width': 0.0001,
        'height': 0.0001,
        'opacity': 0,
        'events': 'no'
      });
```

**Comment by maxkfranz** [comment]
Yes, that's exactly what I expected you were thinking about.  However, edgehandles doesn't *drag* any nodes.  There is no `drag` event for edgehandles, and there can't be.  So either the autopan extension could have added support for general `position` events or maybe autopanning on general position events (or maybe any event or callbacks) is an idea for a completely new extension.  You'd have to ask the author of the autopan extension.  I don't own it.
