### ISSUE TITLE
Check in stop whether it was complete or incomplete

### ISSUE THREAD

**Issue by EHadoux** [cytoscape/cytoscape.js-edgehandles#126]
Hello,

I am trying to run a layout to reorganise the nodes when I add an edge with the handles.
When doing it in the ```complete``` callback the nodes are moved with the layout, but not the edges that stay in place.
In the ```stop``` callback, it works perfectly, but is also called on incomplete adding.
I don't really know what happens (or rather does not happen) between the ```complete``` and the completed ```stop``` (maybe something like the handle is not removed yet at the ```complete``` stage so it's taken into account for the layout).
So is there an easy way to check whether the ```stop``` call is done in a complete or incomplete state?

Thanks!

**Comment by maxkfranz** [comment]
I would welcome a PR to make the signature of the `stop` callback the same as `complete`.

**Comment by EHadoux** [comment]
Alright, sure. If that's not urgent though I put that on my backlog to take care of it a bit later as I don't need it right now.
