### ISSUE TITLE
Warning in console once I create an edge

### ISSUE THREAD

**Issue by ketysek** [cytoscape/cytoscape.js-edgehandles#127]
Hi there, I've recently updated cytoscape to 3.6.0 and also edgehandles plugin to 3.5.0 and now I'm receiving following warning when I create edges:

> Setting a `style` bypass at element creation is deprecated

**Comment by maxkfranz** [comment]
That was resolved in this commit: https://github.com/cytoscape/cytoscape.js-edgehandles/commit/f9f21e71cd9b157fbf268834c38909670c47ef94#diff-6c736af8325583e4149d05c6afe0bd00
