### ISSUE TITLE
Edges don't follow moving nodes 

### ISSUE THREAD

**Issue by ketysek** [cytoscape/cytoscape.js-edgehandles#128]
Hi there :) I've updated cytoscape from 3.2.16 to 3.6.0 and edgehandles from 3.4.1 to 3.5.0 and accidentally my code stopped working properly. 

**Context**: I'm using react and when some change in chart occur (node move, edge create, edge delete), I'm calling my `renderDag` method which checks all the chart visual settings (according to response from API) and calls

```
this.cy.json({
      elements: elements
        .concat(edges)
    })
```

to re-render the chart. This approach stopped working after update edgehandles library. It now works only for first time (for example when I do first drag 'n' drop) but with every other chart change the edges remain untouched. Look at the gif animation. What has been changed so the code stopped working?

![edgebug](https://user-images.githubusercontent.com/11921885/57605908-0b692700-7568-11e9-9b1b-d6b233399eea.gif)

**Comment by maxkfranz** [comment]
Thanks for the information.  Unfortunately, there's no way to tell what's wrong without a reproducible test case or demo.

**Comment by ketysek** [comment]
sorry, it's not related to edgehandles, will open the issue in cytoscape github repo

**Comment by maxkfranz** [comment]
Sounds good
