### ISSUE TITLE
Drawing label with rendering edges

### ISSUE THREAD

**Issue by Kutkov** [cytoscape/cytoscape.js-edgehandles#131]
Hello
When I add a new edge, "ghost edge" is displayed with the label, then the "complete" function  removes the other edges of the node. After that, the edges are redrawn taking into account the new number of edges, and the **label remains** in place of "ghost edge".
![1](https://user-images.githubusercontent.com/29865209/62637092-7d70c280-b943-11e9-85d8-de2834e648db.png)
![2](https://user-images.githubusercontent.com/29865209/62637107-8497d080-b943-11e9-81a1-af8e35e684b5.png)
![3](https://user-images.githubusercontent.com/29865209/62637115-8792c100-b943-11e9-9805-26b5de0139b4.png)
My "complete" function:
```js
complete ( sourceNode, targetNode, addedEles ) {
      if (sourceNode.data('id') === 'j') {
        sourceNode.connectedEdges().filter((e) => {
          return e.source().same(sourceNode) && e.data('type') === addedEles.data('type')
        }).difference(addedEles).remove()
      }
    }
```

**Comment by maxkfranz** [comment]
You probably shouldn't be modifying the graph while the gesture cycle hasn't reached its end (stop).
