### ISSUE TITLE
Usage with ngCytoscape

### ISSUE THREAD

**Issue by SanderBreivik** [cytoscape/cytoscape.js-edgehandles#132]
This is probably not the right place to write this issue, but since ngCytoscape is not maintained I was wondering if someone here has used ngCytoscape in unison with edgehandles. If so, how did you go about registrering the extention?

**Comment by Roconda** [comment]
Hi Sander,

I'm using this extension with react. My solution might not work for you but I managed to get it working using the following snippet:

```js
import Cytoscape from 'cytoscape';
import edgehandles from 'cytoscape-edgehandles';
import CytoscapeComponent from 'react-cytoscapejs';

Cytoscape.use(edgehandles);

function setCytoscape(cy){
    const edgeHandlerSettings = { /* edge handler config object */ }
    cy.edgehandles(edgeHandlerSettings).enableDrawMode();
}

fuction render() {
  return <CytoscapeComponent
               /* some props */
               cy={cy => setCytoscape(cy)} />
}
``` 

Hope something similar works for you as well.

**Comment by SanderBreivik** [comment]
`<cytoscape graph-extensions="[{extension: 'edgehandles', options: ehOptions}] />` seems to do it. Make sure you actually clone from the github, not on bower as it is not updated.
