### ISSUE TITLE
'eh-hover' not implemented

### ISSUE THREAD

**Issue by umdstu** [cytoscape/cytoscape.js-edgehandles#139]
I've actually tried to implement this a couple of different ways myself as I wanted this behavior, but could never get it to work. While working on the PR for another issue, I noticed the `eh-hover` class documented in the README, but the class is never added to the handle, only removed in the `stop()` function. I don't even see where the hover event is emit'ed for the handle.

TLDR; `.eh-hover` doesn't actually seem implemented.

**Comment by maxkfranz** [comment]
I think this may be just a holdover from before some refactoring.  After the refactoring, I think that the hover class may be redundant with the target class.  There are also better events and callbacks now, so adding custom classes is much easier.

Is there a case for having a hover class in addition to the target class?

**Comment by umdstu** [comment]
Understood.

And I"m not sure. What are the options currently?
- add an `.on('mouseover', 'node')` event listerner that checks to see if the target has an `.eh-handle` class, and if it does, perform some action ( add a class?)
- overwrite the .eh-handle class in the stylesheet

Possible options:
- Maybe a `hoverover()` and `hoverout()` event listering specifically for the handle we can hook into in the options.
-  Add an `.eh-hover` class to the handle.

The second would let you modify the stylesheet for that class. At which point maybe functions for handleParams() would make sense (which I already added to the PR for #138)
