### ISSUE TITLE
Remove the handle node

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-edgehandles#143]
Motivation:

- Using a node as the handle UI works OK, but it's not semantically consistent.  The node isn't meaningful.
- Most users don't understand handles.  Most users aren't familiar with this kind of UI.  Apps like Visio use them, but those apps aren't mainstream.  Most users prefer to use draw mode with a button.

Implications:

- There would be no out-of-the-box handle UI.
- A consumer of this library could use something like `cytoscape-popper` to create a handle UI.  Public functions within this extension, like `start()` can be used to kick off the gesture from a custom handle UI.
- This extension would be much simpler.
- This may merit a new extension name, like `cytoscape-connect` or `cytoscape-edge-drawing`.
- There could be a demo.html file that includes an example with a popper handle.

**Comment by TimNZ** [comment]
@maxkfranz  I don't know how you came to this view "Most users don't understand handles. Most users aren't familiar with this kind of UI. Apps like Visio use them, but those apps aren't mainstream. Most users prefer to use draw mode with a button.", 
but it is not representative of of any of the many diagraming tools I've used.
Handles/ports UI/UX in a range of tools are generally similar - Visio, Lucidchart, geru.com.

**Comment by maxkfranz** [comment]
It depends on the audience.  The population of all users for all potential apps has mostly novices.  For a population of advanced users that have used Visio before, the handle may make sense.

In any case, the use of a node as the handle is a bit hacky and should be removed.  If someone wants to create a handle in future, it's simple to do so using Popper and the functions in this extension (like `start()`).

**Comment by TimNZ** [comment]
I agree with a node as a handle isn't ideal, and will use this base for an alternative soon.
More likely to go the custom canvas way to overlay, as I want diagramming tool like functionality.

GREAT work on Cytoscape, thanks to you and the team for making such a great library.

**Comment by blazespinnaker** [comment]
I am still struggling to make this work in a way that isn't frustrating.  Am I missing something?  I've set the border on eh-handle to zero and increased the hover delay, but sometimes I still find I am drawing edges when I don't wish to be and it's not clear where I need to click so as not to start the edge action.  It is particularly problematic when zoomed out and the nodes are smaller.   

As I noted in the previous bug, this issue occurs dramatically in the demo provided in github.

**Comment by maxkfranz** [comment]
> I am still struggling to make this work in a way that isn't frustrating. Am I missing something? I've set the border on eh-handle to zero and increased the hover delay, but sometimes I still find I am drawing edges when I don't wish to be and it's not clear where I need to click so as not to start the edge action. It is particularly problematic when zoomed out and the nodes are smaller.
> 
> As I noted in the previous bug, this issue occurs dramatically in the demo provided in github. Being able to activate the edging from a menu option would be one way to fix this problem.

As suggested in the top of the issue, it would be best to simplify things by removing the handle node completely from this extension.  Extension consumers would be responsible for creating handles (e.g. via popper) or for starting the gesture otherwise (e.g. with a button).  If you're interested in this issue, a pull request to remove the handle node would be welcome.  It would mostly involve deleting existing code and preparing a demo that manually creates handles (e.g. with the popper extension).

**Comment by blazespinnaker** [comment]
Hmmm, I reviewed it and compared it to some of the other extensions.  I think the code is in need of a more dramatic rewrite.   For now, I have removed the library from our code base and use this instead:

 else if (e.target != null && pressedKeys[51]) {
            var nds=cy.elements(":selected");
            cy.add({group: 'edges', data: {source: nds[0].data('id'), target:e.target.data('id')}});
          }
