### ISSUE TITLE
Importing as ES module without NPM

### ISSUE THREAD

**Issue by geajack** [cytoscape/cytoscape.js-edgehandles#145]
I don't want to use NPM for my project. Is there a file I can just save to my source code directory and import as an ES module as in the demo code? I tried this with [cytoscape-edgehandles.js](https://github.com/cytoscape/cytoscape.js-edgehandles/blob/master/cytoscape-edgehandles.js), but it doesn't appear to be an ES-style module.

**Comment by maxkfranz** [comment]
This extension does not support ESM yet.

There's [a Rollup config from the main lib](https://github.com/cytoscape/cytoscape.js/blob/v3.14.1/rollup.config.js) that could be a useful reference, and it seems there is [a Babel plugin that could be used to automate the conversion of `require()` to `import`](https://github.com/tbranyen/babel-plugin-transform-commonjs).

If you're interested in making a pull request for ESM support, then I'll try to put aside some time to review it.
