### ISSUE TITLE
Hide A Handle For A Specific Node

### ISSUE THREAD

**Issue by JoshuaeKaiser** [cytoscape/cytoscape.js-edgehandles#150]
The option to hide a handle for a specific node.

This could be done by passing the actual node object the handle is attached to in the functions that run when styles are calculated. That would allow a developer to set width and height to 0 for a specific node if a condition is met.

It could also be implemented by passing something like 'none' to the handlePosition() method.

Cant figure out any other way to achieve this with the current API

**Comment by maxkfranz** [comment]
I think that this would be addressed by #143.  That would make this extension API-only, so you'd be able to display handles on whatever nodes you want (e.g. using popper to create an overlay div) and to exclude whatever nodes you want.

The change itself would be relatively straight forward (just remove all the handle node stuff), but it would need to be tested out in a real-world app.  @JoshuaeKaiser, would you be able to experiment with #143?

**Comment by JoshuaeKaiser** [comment]
@maxkfranz appreciate the quick reply! Will have a play with #143 

Just FYI i just figured out another way to implement this (for anyone searching), A custom "mouseover" event and then run the eh.hide(); method works perfectly. 

`cy.on("mouseover", "node", function(evt) {
        if (evt.target.data().myProperty === 'whatever') {
          eh.hide();
        } 
      });`
