### ISSUE TITLE
Ignore some nodes when creating the edge

### ISSUE THREAD

**Issue by bernuau** [cytoscape/cytoscape.js-edgehandles#156]
Hi, thank you for your great job.
I have one request though : 
Add a function that would be called before hovering a node, returning true or false. If returning false, the hovered node would be ignored, hence the user wouldn't be able to create the edge to this node.
For example the function could be onEnteringNode(sourceNode, targetNode) and would return true to let the user drop on this targetNode, or false to block this targetNode. Of course, if blocked, the targetNode style would not be changed so that the user understands that he can't create a link between these two nodes. If the user drops on this node, it would cancel the creating of this edge.

**Comment by maxkfranz** [comment]
Have you reviewed the existing options?  If I understand your description correctly, this should already be possible on both the source and target sides.

**Comment by luisflpereira** [comment]
@bernuau you can use the 'edgeType' option.

```
edgeType: function( sourceNode, targetNode ){
    // can return 'flat' for flat edges between nodes or 'node' for intermediate node between them
    // returning null/undefined means an edge can't be added between the two nodes
    return 'flat';
  },
```
