### ISSUE TITLE
When 'edgeType = node' using node mode, this will cause an error if the default value is not used

### ISSUE THREAD

**Issue by 1pbSolidDrives** [cytoscape/cytoscape.js-edgehandles#158]
* When  'edgeType = node' using node mode, this will cause an error if the default value is not used
![image](https://user-images.githubusercontent.com/17431924/117846860-68615a00-b2b4-11eb-9770-07234eacf2b5.png)

**Comment by maxkfranz** [comment]
Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.
