### ISSUE TITLE
An extra wide edge appears when dragging a new edge

### ISSUE THREAD

**Issue by yaxue1123** [cytoscape/cytoscape.js-edgehandles#159]
I'm using cytoscape.js in a React app and trying to integrate the extensions like edgehandles. 

But the extension edgehandles isn't behaving correctly that an extra wide edge appears when dragging a new edge. This extra edge doesn't disappear even after the new edge is added: 

![WechatIMG160](https://user-images.githubusercontent.com/37635744/118012872-831ce880-b31f-11eb-992f-62899ddce165.png)

Also, the extra wide edge's target point doesn't move as I drag the corresponding node:

![WechatIMG161](https://user-images.githubusercontent.com/37635744/118014069-cf1c5d00-b320-11eb-9d87-ae315ec0c8b1.png)

**Comment by maxkfranz** [comment]
Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.
