### ISSUE TITLE
What can I use to turn edgehandlers off in certain conditions?

### ISSUE THREAD

**Issue by fsogutcen** [cytoscape/cytoscape.js-edgehandles#162]
My nodes are not unlocked even if I destroy the edge handles and some arrow previews occur. I use eh.destroy(); depending on state in React; but i cant grab nodes.

Is there an example where I can turn it on or off according to certain conditions?

**Comment by chriszirkel** [comment]
I had a similar problem and solved it via `eh.enable()` and `eh.disable()`
