### ISSUE TITLE
Console error in official demos - Error this.canConnect is not a function

### ISSUE THREAD

**Issue by abulka** [cytoscape/cytoscape.js-edgehandles#163]
I'm getting this error dozens of times in the console in both the official demos and my own code.

    cytoscape-edgehandles.js:784 Uncaught TypeError: this.canConnect is not a function

For example look in the console when running the official demo https://cytoscape.org/cytoscape.js-edgehandles/demo-snap.html, and simply mouse over any node to generate the error in the console.

It happens when options are passed into the initialisation
```js
var eh = cy.edgehandles({
  snap: false
});
```
If you initialise with a no options, there is no error.
```js
var eh = cy.edgehandles({});
// or
let eh = cy.edgehandles();
```

Even when I pass in options that define a `canConnect` function, as per the [readme documentation](https://github.com/cytoscape/cytoscape.js-edgehandles#initialisation) the error still happens?

**Comment by maxkfranz** [comment]
Good catch.  This doesn't affect the UX in any way (i.e. it works fine for end-users in any case), which is probably why it went unnoticed in testing.

Patched in v4.0.1
