### ISSUE TITLE
How to get the source node

### ISSUE THREAD

**Issue by schmorfbert** [cytoscape/cytoscape.js-edgehandles#166]
Hi, 

we currently are trying to get the underlying node of the edgehandle while listening for the "cxttapstart" or "rightclick" event. We currently have no idea, as the event does not seem to contain any information about the node it was triggered on.

Can you maybe provide us with some directions on how to get the information we need?

Thanks in advance and kind regards
kuehso

**Comment by schmorfbert** [comment]
We found a workaround for our problem. We can use the function for commands instead of the commands array, which allows us to check for the classes of the element we opened the menu on. If classes()[0] is 'eh-handle', we return an empty array, otherwise we return our commands. It's not the best way to achieve this I guess, but it seems to work (at least as long as the classes are not renamed).

**Comment by schmorfbert** [comment]
This shouldn't really be closed as the issue still exists. The workaround i mentioned still works, but I think this should not be the actual solution.

**Comment by maxkfranz** [comment]
I don't think this is an issue anymore as the consumer is responsible for creating the handle in the latest release, e.g. with Popper as in the [demo](https://cytoscape.org/cytoscape.js-edgehandles/).
