### ISSUE TITLE
ehcomplete event is emitted before removing ghost elements

### ISSUE THREAD

**Issue by leonbloy** [cytoscape/cytoscape.js-edgehandles#173]
I'm capturing the ehcomplete event, with the intent of reporting the full edges collection to the parent, after an edge has been added.

Unfortunalely, the event is called before the ghost elements are removed, then when the event handler calls `cy.edges()` it finds spurious (ghosts) edges 

```
  this.makeEdges();  // <--- this emits ehcomplete 
  ghostEles.remove();
```

I'm not sure if this inconvenience is easy to fix.

**Comment by maxkfranz** [comment]
That sounds like an interesting revision.

Pull requests for new features are welcome, and we have [instructions for contributors](https://github.com/cytoscape/cytoscape.js/blob/unstable/.github/CONTRIBUTING.md) and a [blog post](https://blog.js.cytoscape.org/2017/06/13/contributing/) that describe how to contribute a pull request.

If you have any questions, don't hesitate to ask.  You can post your questions in this issue, or you can start a discussion in the [discussions section](https://github.com/cytoscape/cytoscape.js/discussions).

It looks like there are two places re. complete in `src`: https://github.com/cytoscape/cytoscape.js-edgehandles/search?q=complete  That's a good starting point.
