### ISSUE TITLE
Missmatch in @types/cytoscape-edgehandles function argument type

### ISSUE THREAD

**Issue by andresmgsl** [cytoscape/cytoscape.js-edgehandles#176]
Hi everyone,

I have a bug using the EdgeHandlesInstance _'start'_ function, caused by the sourceNode argument type.  Reading the code I saw that the _'start'_ function use the _'canStartOn'_ function to do some verifications

![Screenshot from 2022-09-18 01-02-02](https://user-images.githubusercontent.com/6069831/190880118-61fc3572-3d15-4840-ad37-24e164a5a9d0.png)

But the argument it needs is not a string (like the type _@types/cytoscape-edgehandles_ suggests ), it needs an EdgeSingular o something like that to use the noempty() function. 

![Screenshot from 2022-09-18 01-02-16](https://user-images.githubusercontent.com/6069831/190880128-d6611d6b-e0ec-4d2a-bcb2-cea9fd007fb5.png)

This is the type of definition 

![Screenshot from 2022-09-18 01-04-48](https://user-images.githubusercontent.com/6069831/190880178-f0a7c2c8-4e39-403d-9f30-8e1168badc2a.png)

I'm using these versions: 
"@types/cytoscape-edgehandles": "^4.0.0",
"cytoscape-edgehandles": "^4.0.1",

Should I do a pull request and fix the type? or is something I'm doing wrong? 

Thanks in advance

**Comment by maxkfranz** [comment]
It looks like [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) would be the right place to make a PR.

**Comment by andresmgsl** [comment]
Okay, I would do that. 

This issue does not make sense anymore, so I will close it

Thanks.
