### ISSUE TITLE
Move edges

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-edgehandles#18]
See https://github.com/cytoscape/cytoscape.js/issues/281

Use with new APIs to make "moving" edges convenient

**Comment by sirbris** [comment]
In some scenarios with many nodes it's hard to see, where exactly the line is coming from or where it leads to. Would it be possible to add edge handles (specifically to edge type taxi), so the user can modify where the right angles are located?

**Comment by maxkfranz** [comment]
> In some scenarios with many nodes it's hard to see, where exactly the line is coming from or where it leads to. Would it be possible to add edge handles (specifically to edge type taxi), so the user can modify where the right angles are located? 

That's an interesting idea. It might be a better fit for this extension, where you edit the edge points (e.g. mid point):

https://www.npm js.com/package/cytoscape-edge-editing

If you have a proposal specifically for this extension, you're welcome to describe it in more detail in an issue.

**Comment by sirbris** [comment]
Thank you for the link, did not know about that extension. Looks promising, I'll try to figure this out!
