### ISSUE TITLE
Reason for removed Edgehandles not clear, willing to contribute.

### ISSUE THREAD

**Issue by til2000** [cytoscape/cytoscape.js-edgehandles#184]
Hi, 

related to  #171
I see the eh-handle being removed in v4.0.0 and I don't understand the background of that decision.

I could imagine that with a focus on touch devices `over` events are not really the same as with pointer devices, nevertheless the handle provides a big benefit for me, and I went to v3.6.0 to have it again - working with tap events to show the handle.

If there's something that could be contributed - or a showstopper which I can't see, I'm happy to hear. 

thanks!

**Comment by maxkfranz** [comment]
There's a demo with handles already.

**Comment by til2000** [comment]
> There's a demo with handles already.

yes, and the demo relies on enabling drawmode.
I started using edgehandles at version 2.x and was very pleased with the red dot (ie edgehandle?) 
with version 4 it disappeared and the demos don't contain the edgehandle anymore, if I understand correctly 

edit to add:
the demos I checked are the ones mentioned in the readme:
```
This extension allows for drawing edges between nodes ([demo](https://cytoscape.github.io/cytoscape.js-edgehandles/), [demo (snapping disabled)](https://cytoscape.github.io/cytoscape.js-edgehandles/demo-snap.html), [compound demo](https://cytoscape.github.io/cytoscape.js-edgehandles/demo-compound.html), [compound demo (snapping disabled)](https://cytoscape.github.io/cytoscape.js-edgehandles/demo-compound-snap.html))
```

**Comment by til2000** [comment]
@maxkfranz I haven't been able to follow up in time, if you'd like this issue could be reset to open.

**Comment by maxkfranz** [comment]
Reopened and pinned.

**Comment by til2000** [comment]
@maxkfranz I'm still not sure about the reason why the little red dot was removed with version 4.0
I currently am on 3.6 which still has it and I love the functionality, my project highly depends on it.

If I can contribute somehow to either add it behind a feature flag or to add it in general, please let me know.
thanks!

**Comment by maxkfranz** [comment]
You can still do that, *and* you can use whatever graphic you'd like in place of a red dot.

1. Open the demo: https://cytoscape.github.io/cytoscape.js-edgehandles/
2. Click the 'Use custom popper handles' button
3. Hover over a node

If you'd like to contribute a demo that makes this example more prominent (i.e. without a button click), you're welcome to put up a PR.  A strong note in the readme pointing to the new demo would also be useful.

**Comment by til2000** [comment]
Ok, it works with Chrome, doesn't work with Firefox.

I'll look into adding a hover event to compensate the button click.
