### ISSUE TITLE
Default edge handles not shown anymore

### ISSUE THREAD

**Issue by sirbris** [cytoscape/cytoscape.js-edgehandles#188]
I'm using current Chrome Browser and the demo page https://cytoscape.org/cytoscape.js-edgehandles/ does not show the handles anymore on hover. Only when I use the popper extension but not by default. Do you have an idea what changed? Thank you very much in advance

**Comment by maxkfranz** [comment]
You can make your own handles now, with Popper or however else you like.  It's not limited to a dot anymore.

**Comment by sirbris** [comment]
How could I achieve the old behaviour without including Popper or so?

**Comment by UBarodzich** [comment]
Same problem, is there a simple solution?
