### ISSUE TITLE
Wrong Repo link in npm js

### ISSUE THREAD

**Issue by til2000** [cytoscape/cytoscape.js-edgehandles#190]
Minor thing, just for completeness:

https://www.npmjs.com/package/cytoscape-edgehandles

has links for repo and webpage to:
https://github.com/cytoscape/edgehandles

instead of 
https://github.com/cytoscape/cytoscape.js-edgehandles

**Comment by maxkfranz** [comment]
Already updated in package.json: 

https://github.com/cytoscape/cytoscape.js-edgehandles/blob/master/package.json
