### ISSUE TITLE
Custom popper handles select all text on the page

### ISSUE THREAD

**Issue by Hoogkamer** [cytoscape/cytoscape.js-edgehandles#191]
Hi, there are 2 issues with the custom popper handles:
- When starting dragging from the handle all text gets selected
- When dragging second time the ghost edge does not appear and cursor shows no-drop icon

notes:
- Tested with Edge and chrome on windows
- It seems to be a recent problem

Reproduce:
- go to first demo link
- choose "use custom popper handles"
- then drag from the handle to a different node to create an edge
![image](https://github.com/user-attachments/assets/afa93c08-8439-4760-8545-b89e254d928a)

**Comment by maxkfranz** [comment]
@Hoogkamer, would you make a PR to address the demo?

The code for custom handles is up to the app, and the demo is just a simple example.  There will always be customisations needed, depending on the app itself.

That being said, you're welcome to add a workaround for this particular issue in a PR if you like.  It probably just needs a `preventDefault()`.

**Comment by Hoogkamer** [comment]
Ok, thanks for the explanation.
I now use a normal node, so I don't need popper anymore

**Comment by tonymullen** [comment]
> Ok, thanks for the explanation. I now use a normal node, so I don't need popper anymore

Are you able to share any further insights into your solution? I'm having a hard time mimicking the functionality of this demo.
