### ISSUE TITLE
Would like to submit a PR for z-index issue->

### ISSUE THREAD

**Issue by RandallGit** [cytoscape/cytoscape.js-edgehandles#26]
The hard-coded z-index of 999 on the edgehandles canvas element causes stacking/layout issues. 
Example: the graph is used inside of a component that has an action bar with drop-down menus. When cytoscape-edgehandles is initiated the canvas element is rendered above everything including the drop-downs. The drop-down actions are no longer functional because the canvas captures the pointer events.

I have a couple of suggested fixes if there is a way to submit a PR.

Thanks for the plugin!

**Comment by maxkfranz** [comment]
Sounds like either the menu or the edgehandles canvas needs to have their z-index adjusted.  If you'd like to make a PR for adding a z-index option to edgehandles, that would be great!

**Comment by RandallGit** [comment]
Thanks! Will do.
