### ISSUE TITLE
Mobile supports for edgehandles

### ISSUE THREAD

**Issue by robinsswei** [cytoscape/cytoscape.js-edgehandles#29]
Edgehandles works fine on web browser. But it doesn't work on mobile browser. Is there any solution for support mobile web browser? Can I bind new cytoscape's event listener with edgehandles? e.g: double tap

**Comment by maxkfranz** [comment]
You can use the commands to toggle draw mode. It up to you when to call them (e.g. gesture, button, etc)

Refer to the demo (draw mode buttons) and the docs

**Comment by robinsswei** [comment]
Thank you very much. It works now.
