### ISSUE TITLE
Add selector to options

### ISSUE THREAD

**Issue by aschriner** [cytoscape/cytoscape.js-edgehandles#3]
It would be great to be able to specify a selector to limit which nodes get the edgeHandles behavior.  Unless I'm missing something that functionality is not currently available right>?

**Comment by OlmoDalco** [comment]
> Use `handleNodes`, either as a selector or as a filter function (for more complex behaviour).
I am trying to create handles for some of my nodes, depending on their classes attribute. So far without any success. Could you provide an example for a more complex behaviour?
