### ISSUE TITLE
Breaks with cytoscape.js v2.7.1 

### ISSUE THREAD

**Issue by clemsos** [cytoscape/cytoscape.js-edgehandles#33]
Just filling a bug but I see you didn't update the version number yet, so seems normal

* cytoscape.js?2f17fa0…:4432 Uncaught TypeError: Cannot read property '_private' of undefined
* cytoscape.js?2f17fa0…:2328 Uncaught TypeError: Cannot read property 'size' of undefined

breaks on line 4432 when selecting a node

```
      if( badSourceOrTarget ){ removeFromElements(i); continue; } // can't create this

      var src = cy.getElementById( data.source );
      var tgt = cy.getElementById( data.target );

      src._private.edges.push( edge );
      tgt._private.edges.push( edge );
```

then 2328 when trying to select another one

```
    for( var i = 0; i < this.length; i++ ){
      var ele = this[ i ];
      var parent = cy.getElementById( ele._private.data.parent );

      if( parent.size() > 0 ){
        parents.push( parent );
      }
    }
```

![selection_127](https://cloud.githubusercontent.com/assets/743246/15748256/7572d2ec-28de-11e6-9565-f14192cd56d6.png)

**Comment by maxkfranz** [comment]
@clemsos It seems to work OK for me with 2.7.2.  Do you still notice the issue?

**Comment by maxkfranz** [comment]
Oops, didn't mean to close...

**Comment by maxkfranz** [comment]
@clemsos The extension seems to work OK with the latest Cy release and extension release.  Closing for now
