### ISSUE TITLE
Edgehandles canvas not resizing on Cy resize

### ISSUE THREAD

**Issue by megawebmaster** [cytoscape/cytoscape.js-edgehandles#36]
Hi!

I've found out that when Cytoscape resizes its canvas there are places I cannot use edge handles to create connections. It seems we are missing resizing after cy.resize() :)

We need to add:
```
cy.on( 'resize', function() {
    $container.trigger( 'cyedgehandles.resize' );
});
```

on line 417 ;)

**Comment by maxkfranz** [comment]
Merged and released as 2.4.3

Thanks!
