### ISSUE TITLE
Avoid multiple edges between same two nodes

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js-edgehandles#39]
It is possible to add multiple edges between the same two nodes.

How can I disable this, so I am sure a user can never add the same edge multiple times?

**Comment by maxkfranz** [comment]
Set `edgeType` to return null for any two nodes who have existing edges :
```js
...
edgeType: function( sourceNode, targetNode ) {
  return sourceNode.edgesWith( targetNode ).empty() ? 'flat' : null;
},
...
```

See edgesWith : http://js.cytoscape.org/#nodes.edgesWith

**Comment by roddc** [comment]
> Set `edgeType` to return null for any two nodes who have existing edges :
> 
> ```js
> ...
> edgeType: function( sourceNode, targetNode ) {
>   return sourceNode.edgesWith( targetNode ).empty() ? 'flat' : null;
> },
> ...
> ```
> 
> See edgesWith : http://js.cytoscape.org/#nodes.edgesWith

Hi, but this method doesn't trigger complete method

**Comment by maxkfranz** [comment]
If an edge isn't created, then the gesture hasn't completed.  I'm not sure that `complete()` would be appropriate.

**Comment by roddc** [comment]
> If an edge isn't created, then the gesture hasn't completed. I'm not sure that `complete()` would be appropriate.

But an edge was created and after that the complete() didn't get called
