### ISSUE TITLE
I need a version without jquery

### ISSUE THREAD

**Issue by tongbin** [cytoscape/cytoscape.js-edgehandles#40]
I'm working on a react/redux project which need one version without jquery, and I've started a project which is at 

https://github.com/tongbin/cytoscape.js-edgehandles

please let me know if there is any problems with it.

**Comment by maxkfranz** [comment]
The only reason jQuery was ever used in some UI extensions was for IE support.  That's probably not important anymore, so we can just merge this in by pull request if you like.

Those who really want IE support can stay on an older version.

A couple of errors when trying the `demo.html` in your repo:

(1) References to `originalEvent`.  Every `x.originalEvent` should probably just be `x`

(2) Probably need a `.off()` wrapper

Thanks

**Comment by tongbin** [comment]
Thanks a lot for your code review, I'll fix these issues.
