### ISSUE TITLE
Dropping ghost edge when moving mouse throws an error 

### ISSUE THREAD

**Issue by Andreew4x4** [cytoscape/cytoscape.js-edgehandles#46]
`cytoscape-edgehandles.js:623 Uncaught TypeError: Cannot read property 'id' of null(…)`

When handleLineType = ghost and I start creating egde from source node then release mouse button while still moving the mouse - somewhere between the nodes or out of canvas. Throws an error

**Comment by maxkfranz** [comment]
@Andreew4x4 I'm not able to reproduce this on the demo.html page on master with `cy.edgehandles({ handleLineType: 'ghost' });`.  Would you please provide some more information so I can reproduce the issue as you have?

**Comment by Andreew4x4** [comment]
Google Chrome:  54.0.2840.9 (64-bit)
System:  54.0.2840.90 (64-bit)
Reproduced on demo file from master: [Video](https://www.dropbox.com/s/o345whitr0g1y58/vokoscreen-2016-11-10_10-17-44.mkv?dl=0)

**Comment by maxkfranz** [comment]
Reproducible very rarely on openSUSE Tumbleweed (Gnome) on Chromium 54.0.2840.71 (64-bit)

Saved the stack trace so should be able to have a fix

**Comment by maxkfranz** [comment]
Fix published as 2.6.2
