### ISSUE TITLE
readme.md mistake

### ISSUE THREAD

**Issue by Spannella** [cytoscape/cytoscape.js-edgehandles#47]
All function can be called via cy.edgehandles('function-name'):

cy.edgehandles('enable') : enable the extension
# cy.edgehandles('enable') : disable the extension
cy.edgehandles('option', 'preview', false) : set individual option (e.g. 'preview')
cy.edgehandles('option', { /* options */ }) : set all options
cy.edgehandles('option', 'preview') : get option value (e.g. 'preview')
cy.edgehandles('destroy') : destroy the extension instance
cy.edgehandles('start', 'some-node-id') : start the handle drag state on node with specified id (e.g. 'some-node-id')
cy.edgehandles('drawon') : enable draw mode
cy.edgehandles('drawoff') : disable draw mode

**Comment by maxkfranz** [comment]
Thanks!
