### ISSUE TITLE
Error when taking #cy "position" is "relative"

### ISSUE THREAD

**Issue by truongvu2106** [cytoscape/cytoscape.js-edgehandles#51]
I take `<div id="cy"></div>` position is relative and I scroll down the scroll bar (it's not on top). I cannot connect 2 nodes together.

I think we have a problem with "mdownHandler" function about calculated height and top offset page.

Could you consider this issue.

Thanks

**Comment by truongvu2106** [comment]
Someone help me resolve this issue, please?
Thanks

**Comment by maxkfranz** [comment]
Fix pushed to `cytoscape-edgehandles@2.7.1`
