### ISSUE TITLE
Strange edge-arrow behaviour when drawing non-circle nodes

### ISSUE THREAD

**Issue by lszanto** [cytoscape/cytoscape.js-edgehandles#54]
Just came across this and after a bit of testing I think i've found what seems to be the cause of the issue. As you can see below when using node shapes other than circle when you reduce the border-width to 0 then when you are dragging the edge you occasionally get the arrow flipping around which way it is facing. You can easily recreate this with the demo.html in the repo by simply adding 'shape': 'rectangle' to the node style.

With border-width set to 2px:
![proper](https://cloud.githubusercontent.com/assets/139145/21085467/a0679b16-c066-11e6-9ca6-75c9bac4b222.png)

With border-width set to 0:
![bad](https://cloud.githubusercontent.com/assets/139145/21085470/a820b482-c066-11e6-800a-a8fbce88aa51.png)

**Comment by maxkfranz** [comment]
This issue was never reproducible on our end.  Closing
