### ISSUE TITLE
`stop` event not being fired in draw mode

### ISSUE THREAD

**Issue by grigorijski** [cytoscape/cytoscape.js-edgehandles#55]
Stop event not fired in next initialization sequence, only complete is fired when edge is created. Stop not fired not when edge created, not when just handle released

cy.edgehandles({ toggleOffOnLeave: true, handleSize: 0, cxt: true });
cy.edgehandles('drawon');
cy.on('cyedgehandles.stop', 'node', function(e) {
	console.log('stop');
});
cy.on('cyedgehandles.complete', 'node', function(e) {			
	console.log('complete');
})

**Comment by maxkfranz** [comment]
Fixed in 2.8
