### ISSUE TITLE
can this library support multiple handles?

### ISSUE THREAD

**Issue by lukejpreston** [cytoscape/cytoscape.js-edgehandles#58]
can this library support multiple handles?

I would like to be able to have a node which has X number of handles to a node because in my graph nodes can only support X number of edges

**Comment by maxkfranz** [comment]
No, if it's not in the readme it's not supported.  There's a different extension though https://github.com/frankiex/cytoscape.js-edge-editation

**Comment by lukejpreston** [comment]
This library is better. Work around was to make a load of nodes which were the size of edgehandles
