### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by luethia007** [cytoscape/cytoscape.js-edgehandles#59]
Line 540 //var opts = Object.assign({}, defaults, params ); in IE10 not supportet.

**Comment by maxkfranz** [comment]
@mj3cheun Would you please look into this while you're testing the 3.0 API changes for this extension?

Probably you can just paste in a polyfill.

You can use Virtualbox with the VMs here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by mj3cheun** [comment]
Yes sure on it
