### ISSUE TITLE
v2.10.3 and later destroys clickable html components

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js-edgehandles#62]
Hi,
I am using this extension with semver ```~2.10.2```. I realized that clickable html components are not working for me after v2.10.3 of this extension is released. If I switch the semver of this extension to ```2.10.2``` from ```~2.10.2``` then the problem disappears. As far as I see the problem is emerged with https://github.com/cytoscape/cytoscape.js-edgehandles/commit/4b015c7906e33873291b7a5bf1a78434a48d1a83

**Comment by maxkfranz** [comment]
If you have position: static on the cy div, you can't use extensions

**Comment by maxkfranz** [comment]
See also https://github.com/cytoscape/cytoscape.js/issues/1776
