### ISSUE TITLE
Uncaught TypeError: Cannot set property 'mapping' of null

### ISSUE THREAD

**Issue by kubo0212** [cytoscape/cytoscape.js-edgehandles#72]
When I tried to draw line using 'ghost' mode and attribute 'shape' in css, it shown an error:
`Uncaught TypeError: Cannot set property 'mapping' of null`

I changed on your code demo like that:

                           var cy = window.cy = cytoscape({

				container: document.getElementById('cy'),

				ready: function() {},

				layout: {
					name: 'grid',
					rows: 2,
					cols: 2
				},

				style: [{
						selector: 'node',
						css: {
							'content': 'data(name)',
							'shape': 'data(shape)'
						}
					},

					{
						selector: 'edge',
						css: {
							'curve-style': 'bezier',
							'target-arrow-shape': 'triangle'
						}
					},

					// some style for the ext

					{
						selector: '.edgehandles-hover',
						css: {
							'background-color': 'red'
						}
					},

					{
						selector: '.edgehandles-source',
						css: {
							'border-width': 2,
							'border-color': 'red'
						}
					},

					{
						selector: '.edgehandles-target',
						css: {
							'border-width': 2,
							'border-color': 'red'
						}
					},

					{
						selector: '.edgehandles-preview, .edgehandles-ghost-edge',
						css: {
							'line-color': 'red',
							'target-arrow-color': 'red',
							'source-arrow-color': 'red'
						}
					}
				],

				elements: {
					nodes: [{
							data: {
								id: 'j',
								name: 'Jerry',
								shape: 'rectangle'
							}
						},
						{
							data: {
								id: 'e',
								name: 'Elaine',
								shape: 'rectangle'
							}
						},
						{
							data: {
								id: 'k',
								name: 'Kramer',
								shape: 'rectangle'
							}
						},
						{
							data: {
								id: 'g',
								name: 'George',
								shape: 'rectangle'
							}
						}
					],
					edges: [{
							data: {
								source: 'j',
								target: 'e'
							}
						},
						{
							data: {
								source: 'j',
								target: 'k'
							}
						},
						{
							data: {
								source: 'j',
								target: 'g'
							}
						},
						{
							data: {
								source: 'e',
								target: 'j'
							}
						},
						{
							data: {
								source: 'e',
								target: 'k'
							}
						},
						{
							data: {
								source: 'k',
								target: 'j'
							}
						},
						{
							data: {
								source: 'k',
								target: 'e'
							}
						},
						{
							data: {
								source: 'k',
								target: 'g'
							}
						},
						{
							data: {
								source: 'g',
								target: 'j'
							}
						}
					]
				}
			});

What did I do wrong?

**Comment by maxkfranz** [comment]
You can't apply this block to all nodes if you're not the only one creating
nodes (e.g. ghost eles)

```
selector: 'node',
css: {
  'content': 'data(name)',
  'shape': 'data(shape)'
}
```

**Comment by gtarcea** [comment]
How would I apply this to just certain nodes? I also need some styles to have data('xxx') references.

**Comment by maxkfranz** [comment]
Change your selector to only match your nodes, e.g. a class or data existence selectors.

**Comment by kubo0212** [comment]
I had solved them. Thank for your reply and help. I close my solution.
