### ISSUE TITLE
We can draw an edge even if disabled

### ISSUE THREAD

**Issue by anault** [cytoscape/cytoscape.js-edgehandles#74]
I previously fixed a bug where edgehandle would trigger even if the extension was disabled: https://github.com/cytoscape/cytoscape.js-edgehandles/pull/71

Well, I spotted another event (`cxtdrag tapdrag`) that triggers an edge drawing when edgehandle is `enabled: false`.

This makes me think, **should we just cancel/unbind all events when the extension is disabled?**

Steps to reproduce: 
1. Enable edgehandle `cy.edgehandles({/* options */});`
2. Hover a node. The handle should be visible.
3. Unhover the node.
4. Disable the extension `cy.edgehandles('disable');`
5. Hover the **same** node. The handle is not visible.
6. Try to drag that node. It will draw an edge instead of dragging.

**Comment by anault** [comment]
An quick fix would be to:
```
if( disabled() ) {
  return;
}
```
on the `cxtdrag tapdrag` event

**Comment by maxkfranz** [comment]
OK, I'll apply your proposed fix tomorrow

**Comment by maxkfranz** [comment]
Published as 2.13.2
