### ISSUE TITLE
lodash required?

### ISSUE THREAD

**Issue by ckapop** [cytoscape/cytoscape.js-edgehandles#77]
Hi, is lodash required for proper registration?

I noticed this:
`Plain HTML/JS has the extension registered for you automatically, because no require() is needed.`

But I can't get things to work using <src> tags unless lodash is included in my app.

**Comment by maxkfranz** [comment]
Yes, it needs two Lodash mini-packages: https://github.com/cytoscape/cytoscape.js-edgehandles/blob/2.13.2/package.json#L32

If you don't use a modern bundler like browserify or webpack, then you need to include lodash yourself.

**Comment by alvinrindra** [comment]
Hi @maxkfranz , I have already included lodash in my app using requirejs config, but I still got errors by using the current version edgehandles, > v3.3.0

![image](https://user-images.githubusercontent.com/8433469/43651082-b32bb59e-9741-11e8-834a-0ed8e12c073f.png)
