### ISSUE TITLE
append method issue

### ISSUE THREAD

**Issue by ckapop** [cytoscape/cytoscape.js-edgehandles#78]
I was getting alignment issues with the canvas. It was not appending the canvas to the 'child' div of the cyto element creating an offset issue.

When I change:
`append: function(ele) {
        this[0].appendChild( ele[0] || ele );
        return this;
},`
to:
`append: function(ele) {
        this[0].childNodes[0].appendChild( ele[0] || ele );
        return this;
},`

it seems to work as expected. Alignment offsets are fixed now because the **position: 'absolute'**  works because the canvas is a child and not a sibling.

**Comment by maxkfranz** [comment]
The cy div must not be `position: static`.  If that is followed, then the extension should work fine.   You can make no assumptions about the internal dom hierarchy of the cy div.  Those are internal implementation details that can change at any time.
