### ISSUE TITLE
Errors when using edgehandles with cytoscape-dagre.js

### ISSUE THREAD

**Issue by chrodos** [cytoscape/cytoscape.js-edgehandles#80]
When the graph layout is the "dagre" (cytoscape-dagre.js) then edgehandles return a number of errors. I checked the code and the part that adds the ghost node needs to change to something like that to accommodate the faveColor and faveShape data. In case anyone else also faces this issue, goto line 525 and replace the cy.add like this:
`ghostNode = cy.add( {
                    group: 'nodes',
                    data:{faveColor:'#000000',faveShape:'roundrectangle'},
                    classes: 'edgehandles-ghost edgehandles-ghost-node',
                    css: {
                      'background-color': 'blue',
                      'width': 0.0001,
                      'height': 0.0001,
                      'opacity': 0,
                      'events': 'no'
                    },
                    position: {
                      x: 0,
                      y: 0
                    }
                  } );`

I think that in a new version of cytoscape-edgehandles this should be added.

**Comment by maxkfranz** [comment]
This is a problem in your app / stylesheet, not the lib.

The warning message you get in the console is to not use a mapper on elements that don't have the data defined.  Use an existence selectors.  For example, use `[faveColor]` on blocks that use data mappers with `faveColor`.
