### ISSUE TITLE
not working with dynamic background Images on nodes

### ISSUE THREAD

**Issue by jonathanmeguira** [cytoscape/cytoscape.js-edgehandles#82]
I get this error when as soon as I drag from a node 
`core.es5.js:1020 ERROR TypeError: Cannot read property 'value' of null
    at Style.styfn.parseImpl (parse.js:197)
    at Style.styfn.parseImplWarn (parse.js:42)
    at Style.styfn.parse (parse.js:24)
    at Style.styfn.applyParsedProperty (apply.js:445)
    at Style.styfn.applyContextStyle (apply.js:209)
    at Style.styfn.apply (apply.js:38)
    at Collection.updateStyle (style.js:31)
    at Element.elesfn.restore (index.js:468)
    at Element (element.js:99)
    at Core.add (add-remove.js:66)`

and then 
`The style property `background-image: ` is invalid`

my general style for the canvas is ::
` selector: 'node',
      style: {
        'background-color': '#8870EE',
        'border-width': '4px',
        'background-image': 'data(image)',
        'border-color': 'white'
      }`

all nodes have their background properly displayed and all nodes do have an image property.

How can I solve this ? 

FYI: using angular 4

@maxkfranz

**Comment by jonathanmeguira** [comment]
PS: as soon as in the style i replace the images with static url then it has no issue drawing the links and does not complain

**Comment by maxkfranz** [comment]
Your stylesheet is invalid.  Follow what the warning message tells you in the console:  You've defined a style property [mapper](http://js.cytoscape.org/#style/mappers) without ensuring that the mapper is valid for all matching elements in the corresponding selector block.  Again as the warning message suggests, use an existence selector (e.g. `[foo]`).

**Comment by jonathanmeguira** [comment]
awesome thank you
