### ISSUE TITLE
Draw line on node drag without need for handles

### ISSUE THREAD

**Issue by anault** [cytoscape/cytoscape.js-edgehandles#86]
It is possible for a touch `drag` to initiate the handleLine without having to first `tap` the node?

On a computer, you hover the node (creates handle), and drag to create the line.
On a mobile device, you **have to tap the node** (creates handle), and then drag.

I understand that there is no concept of hovering on mobile, but could the handle's "hitbox" just be evaluated when you start dragging?

**Comment by anault** [comment]
Would calling `cyedgehandles.forcestart` solve my issue in the short term? It's undocumented, so I'm being cautious.

**Comment by maxkfranz** [comment]
`forcestart` is in the readme: 

cy.edgehandles('start', 'some-node-id') : start the handle drag state on node with specified id (e.g. 'some-node-id')

**Comment by anault** [comment]
My first thought was to try:

```
cy.on('cxttapstart tapstart', 'node', function(evt) {
    var node = evt.target;
    cy.edgehandles('start', node.id());
});
```

But couldn't get it to work. [Demo](https://codepen.io/anault/pen/Nvwjov?editors=0010)

@maxkfranz Sorry, I really need your help on this one. Do you have an example I could use?

**Comment by maxkfranz** [comment]
I don't think it's meant to be used like that.  Wouldn't you be conflicting with the normal events / workflow of the extension?  You're meant to force start when you don't interact with the node (e.g. click a far away button, or start from a context menu); otherwise you can just use the normal features.

**Comment by anault** [comment]
Yeah, `forcestart` probably isn't the solution.

But how can I **skip the need to first tap the node** (to show the handle) so I can then draw an edge using the normal features?

*Here's my use case:*
*Nodes are undraggable (`autoungrabify: true`). When they are "dragged", it should automatically create an edge instead (desktop and mobile).*

**Comment by maxkfranz** [comment]
Draw mode

There's an example button in the demo

**Comment by anault** [comment]
`cy.edgehandles('drawon');`

Wow, I was overthinking it. That's perfect, thank you!
