### ISSUE TITLE
how to get position of mouse when complete event fires?

### ISSUE THREAD

**Issue by finger563** [cytoscape/cytoscape.js-edgehandles#89]
I want to create a context menu for the user to select a type of edge to create, but the complete event does not provide an event containing the position of the pointer when the mouseup event occurred.

**Comment by maxkfranz** [comment]
I use the target node position.

**Comment by finger563** [comment]
That doesn't work well if the target node's position is outside the `extents` of the cytoscape window

**Comment by finger563** [comment]
for instance in large compound node graphs

**Comment by maxkfranz** [comment]
I see.  I'm usually using Tippy or qTip, which automatically handles that.  I'll take a look at the PR.

**Comment by finger563** [comment]
Any luck getting this rolled into a release? :)

**Comment by maxkfranz** [comment]
Published as 2.15.0
