### ISSUE TITLE
Crashes on IE11 with "Object doesn't support this action"

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js-edgehandles#91]
This occurs on #56 - in the #trigger-function of the jq-replacement, since IE doesn't support `new Event()` - but I'm quite sure this has worked just fine previously? Have I only been dreaming this?

**Comment by maxkfranz** [comment]
It probably worked when it was using jQuery.  You're right that [IE doesn't support the `Event` constructor](https://developer.mozilla.org/en-US/docs/Web/API/Event/Event), but it looks like [older APIs](http://youmightnotneedjquery.com/#trigger_custom) would work.

**Comment by maxkfranz** [comment]
Published as 2.14.1
