### ISSUE TITLE
Calling cy.nodes() not working correct

### ISSUE THREAD

**Issue by CBeuth10** [cytoscape/cytoscape.js-edgehandles#96]
HI,

here is another one. As before, hopefully the correct platform.

It's about the current release. When adding a node to cy container (in my case it is done by drag and drop), the listener "mouseover" is called and because of that show() is called as well. While doing this, a handleNode is added to cy. If I now call cy. nodes(), I will get the handleNode in addition to all visible, correct nodes.
If I add edges between all nodes in my cy container, there is no problem, because the listener "tapend" with function stop() is called and handleNode is deleted.
But if I just add a node without doing something afterwards, I have "too much nodes", because on "mouseover" handleNode is created, but never deleted.

BR

**Comment by maxkfranz** [comment]
If you don't want to include the handle node, then you'll have to use a filter (e.g. `cy.nodes().not('.eh-handle')`).  I've updated the readme with the handle class.
