### ISSUE TITLE
Remove "hover-effect" when mouse out

### ISSUE THREAD

**Issue by ketysek** [cytoscape/cytoscape.js-edgehandles#97]
Hi, I am playing with your example [here](https://cytoscape.github.io/cytoscape.js-edgehandles/) and I would like to remove the red hover dot when mouse cursor is out from the node. Now the red dot stays displayed until you move cursor over another node. How can I achieve this? Thanks!

**Comment by maxkfranz** [comment]
`eh.hide()` removes the handle.

**Comment by ketysek** [comment]
Thanks @maxkfranz but I cannot figure out, how to determine that I'm not hovering any node? There's no event for that if I am right :-(

**Comment by maxkfranz** [comment]
`mouseout`

**Comment by ketysek** [comment]
thank you very much, I figured it out!
